type FileType = {
	mime: string
	name: string
}

export const fileTypes: { [key: string]: FileType } = {
	x3d: { mime: 'application/vnd.hzn-3d-crossword', name: '3D Crossword Plugin' },
	'3gp': { mime: 'video/3gpp', name: '3GP' },
	'3g2': { mime: 'video/3gpp2', name: '3GP2' },
	mseq: { mime: 'application/vnd.mseq', name: '3GPP MSEQ File' },
	pwn: { mime: 'application/vnd.3m.post-it-notes', name: '3M Post It Notes' },
	plb: {
		mime: 'application/vnd.3gpp.pic-bw-large',
		name: '3rd Generation Partnership Project - Pic Large',
	},
	psb: {
		mime: 'application/vnd.3gpp.pic-bw-small',
		name: '3rd Generation Partnership Project - Pic Small',
	},
	pvb: {
		mime: 'application/vnd.3gpp.pic-bw-var',
		name: '3rd Generation Partnership Project - Pic Var',
	},
	tcap: {
		mime: 'application/vnd.3gpp2.tcap',
		name: '3rd Generation Partnership Project - Transaction Capabilities Application Part',
	},
	'7z': { mime: 'application/x-7z-compressed', name: '7-Zip' },
	abw: { mime: 'application/x-abiword', name: 'AbiWord' },
	ace: { mime: 'application/x-ace-compressed', name: 'Ace Archive' },
	acc: { mime: 'application/vnd.americandynamics.acc', name: 'Active Content Compression' },
	acu: { mime: 'application/vnd.acucobol', name: 'ACU Cobol' },
	atc: { mime: 'application/vnd.acucorp', name: 'ACU Cobol' },
	adp: { mime: 'audio/adpcm', name: 'Adaptive differential pulse-code modulation' },
	aab: {
		mime: 'application/x-authorware-bin',
		name: 'Adobe (Macropedia) Authorware - Binary File',
	},
	aam: { mime: 'application/x-authorware-map', name: 'Adobe (Macropedia) Authorware - Map' },
	aas: {
		mime: 'application/x-authorware-seg',
		name: 'Adobe (Macropedia) Authorware - Segment File',
	},
	air: {
		mime: 'application/vnd.adobe.air-application-installer-package+zip',
		name: 'Adobe AIR Application',
	},
	swf: { mime: 'application/x-shockwave-flash', name: 'Adobe Flash' },
	fxp: { mime: 'application/vnd.adobe.fxp', name: 'Adobe Flex Project' },
	pdf: { mime: 'application/pdf', name: 'Adobe Portable Document Format' },
	ppd: {
		mime: 'application/vnd.cups-ppd',
		name: 'Adobe PostScript Printer Description File Format',
	},
	dir: { mime: 'application/x-director', name: 'Adobe Shockwave Player' },
	xdp: { mime: 'application/vnd.adobe.xdp+xml', name: 'Adobe XML Data Package' },
	xfdf: { mime: 'application/vnd.adobe.xfdf', name: 'Adobe XML Forms Data Format' },
	aac: { mime: 'audio/x-aac', name: 'Advanced Audio Coding (AAC)' },
	ahead: { mime: 'application/vnd.ahead.space', name: 'Ahead AIR Application' },
	azf: { mime: 'application/vnd.airzip.filesecure.azf', name: 'AirZip FileSECURE' },
	azs: { mime: 'application/vnd.airzip.filesecure.azs', name: 'AirZip FileSECURE' },
	azw: { mime: 'application/vnd.amazon.ebook', name: 'Amazon Kindle eBook format' },
	ami: { mime: 'application/vnd.amiga.ami', name: 'AmigaDE' },
	apk: { mime: 'application/vnd.android.package-archive', name: 'Android Package Archive' },
	cii: {
		mime: 'application/vnd.anser-web-certificate-issue-initiation',
		name: 'ANSER-WEB Terminal Client - Certificate Issue',
	},
	fti: {
		mime: 'application/vnd.anser-web-funds-transfer-initiation',
		name: 'ANSER-WEB Terminal Client - Web Funds Transfer',
	},
	atx: { mime: 'application/vnd.antix.game-component', name: 'Antix Game Player' },
	mpkg: { mime: 'application/vnd.apple.installer+xml', name: 'Apple Installer Package' },
	aw: { mime: 'application/applixware', name: 'Applixware' },
	les: { mime: 'application/vnd.hhe.lesson-player', name: 'Archipelago Lesson Player' },
	swi: { mime: 'application/vnd.aristanetworks.swi', name: 'Arista Networks Software Image' },
	s: { mime: 'text/x-asm', name: 'Assembler Source File' },
	atomcat: { mime: 'application/atomcat+xml', name: 'Atom Publishing Protocol' },
	atomsvc: { mime: 'application/atomsvc+xml', name: 'Atom Publishing Protocol Service Document' },
	ac: { mime: 'application/pkix-attr-cert', name: 'Attribute Certificate' },
	aif: { mime: 'audio/x-aiff', name: 'Audio Interchange File Format' },
	avi: { mime: 'video/x-msvideo', name: 'Audio Video Interleave (AVI)' },
	aep: { mime: 'application/vnd.audiograph', name: 'Audiograph' },
	dxf: { mime: 'image/vnd.dxf', name: 'AutoCAD DXF' },
	dwf: { mime: 'model/vnd.dwf', name: 'Autodesk Design Web Format (DWF)' },
	par: { mime: 'text/plain-bas', name: 'BAS Partitur Format' },
	bcpio: { mime: 'application/x-bcpio', name: 'Binary CPIO Archive' },
	bin: { mime: 'application/octet-stream', name: 'Binary Data' },
	bmp: { mime: 'image/bmp', name: 'Bitmap Image File' },
	torrent: { mime: 'application/x-bittorrent', name: 'BitTorrent' },
	cod: { mime: 'application/vnd.rim.cod', name: 'Blackberry COD File' },
	mpm: { mime: 'application/vnd.blueice.multipass', name: 'Blueice Research Multipass' },
	bmi: { mime: 'application/vnd.bmi', name: 'BMI Drawing Data Interchange' },
	sh: { mime: 'application/x-sh', name: 'Bourne Shell Script' },
	btif: { mime: 'image/prs.btif', name: 'BTIF' },
	rep: { mime: 'application/vnd.businessobjects', name: 'BusinessObjects' },
	bz: { mime: 'application/x-bzip', name: 'Bzip Archive' },
	bz2: { mime: 'application/x-bzip2', name: 'Bzip2 Archive' },
	csh: { mime: 'application/x-csh', name: 'C Shell Script' },
	c: { mime: 'text/x-c', name: 'C Source File' },
	cdxml: { mime: 'application/vnd.chemdraw+xml', name: 'CambridgeSoft Chem Draw' },
	css: { mime: 'text/css', name: 'Cascading Style Sheets (CSS)' },
	cdx: { mime: 'chemical/x-cdx', name: 'ChemDraw eXchange file' },
	cml: { mime: 'chemical/x-cml', name: 'Chemical Markup Language' },
	csml: { mime: 'chemical/x-csml', name: 'Chemical Style Markup Language' },
	cdbcmsg: { mime: 'application/vnd.contact.cmsg', name: 'CIM Database' },
	cla: { mime: 'application/vnd.claymore', name: 'Claymore Data Files' },
	c4g: { mime: 'application/vnd.clonk.c4group', name: 'Clonk Game' },
	sub: { mime: 'image/vnd.dvb.subtitle', name: 'Close Captioning - Subtitle' },
	cdmia: {
		mime: 'application/cdmi-capability',
		name: 'Cloud Data Management Interface (CDMI) - Capability',
	},
	cdmic: {
		mime: 'application/cdmi-container',
		name: 'Cloud Data Management Interface (CDMI) - Contaimer',
	},
	cdmid: {
		mime: 'application/cdmi-domain',
		name: 'Cloud Data Management Interface (CDMI) - Domain',
	},
	cdmio: {
		mime: 'application/cdmi-object',
		name: 'Cloud Data Management Interface (CDMI) - Object',
	},
	cdmiq: { mime: 'application/cdmi-queue', name: 'Cloud Data Management Interface (CDMI) - Queue' },
	c11amc: {
		mime: 'application/vnd.cluetrust.cartomobile-config',
		name: 'ClueTrust CartoMobile - Config',
	},
	c11amz: {
		mime: 'application/vnd.cluetrust.cartomobile-config-pkg',
		name: 'ClueTrust CartoMobile - Config Package',
	},
	ras: { mime: 'image/x-cmu-raster', name: 'CMU Image' },
	dae: { mime: 'model/vnd.collada+xml', name: 'COLLADA' },
	csv: { mime: 'text/csv', name: 'Comma-Seperated Values' },
	cpt: { mime: 'application/mac-compactpro', name: 'Compact Pro' },
	wmlc: { mime: 'application/vnd.wap.wmlc', name: 'Compiled Wireless Markup Language (WMLC)' },
	cgm: { mime: 'image/cgm', name: 'Computer Graphics Metafile' },
	ice: { mime: 'x-conference/x-cooltalk', name: 'CoolTalk' },
	cmx: { mime: 'image/x-cmx', name: 'Corel Metafile Exchange (CMX)' },
	xar: { mime: 'application/vnd.xara', name: 'CorelXARA' },
	cmc: { mime: 'application/vnd.cosmocaller', name: 'CosmoCaller' },
	cpio: { mime: 'application/x-cpio', name: 'CPIO Archive' },
	clkx: { mime: 'application/vnd.crick.clicker', name: 'CrickSoftware - Clicker' },
	clkk: {
		mime: 'application/vnd.crick.clicker.keyboard',
		name: 'CrickSoftware - Clicker - Keyboard',
	},
	clkp: {
		mime: 'application/vnd.crick.clicker.palette',
		name: 'CrickSoftware - Clicker - Palette',
	},
	clkt: {
		mime: 'application/vnd.crick.clicker.template',
		name: 'CrickSoftware - Clicker - Template',
	},
	clkw: {
		mime: 'application/vnd.crick.clicker.wordbank',
		name: 'CrickSoftware - Clicker - Wordbank',
	},
	wbs: {
		mime: 'application/vnd.criticaltools.wbs+xml',
		name: 'Critical Tools - PERT Chart EXPERT',
	},
	cryptonote: { mime: 'application/vnd.rig.cryptonote', name: 'CryptoNote' },
	cif: { mime: 'chemical/x-cif', name: 'Crystallographic Interchange Format' },
	cmdf: { mime: 'chemical/x-cmdf', name: 'CrystalMaker Data Format' },
	cu: { mime: 'application/cu-seeme', name: 'CU-SeeMe' },
	cww: { mime: 'application/prs.cww', name: 'CU-Writer' },
	curl: { mime: 'text/vnd.curl', name: 'Curl - Applet' },
	dcurl: { mime: 'text/vnd.curl.dcurl', name: 'Curl - Detached Applet' },
	mcurl: { mime: 'text/vnd.curl.mcurl', name: 'Curl - Manifest File' },
	scurl: { mime: 'text/vnd.curl.scurl', name: 'Curl - Source Code' },
	car: { mime: 'application/vnd.curl.car', name: 'CURL Applet' },
	pcurl: { mime: 'application/vnd.curl.pcurl', name: 'CURL Applet' },
	cmp: { mime: 'application/vnd.yellowriver-custom-menu', name: 'CustomMenu' },
	dssc: {
		mime: 'application/dssc+der',
		name: 'Data Structure for the Security Suitability of Cryptographic Algorithms',
	},
	xdssc: {
		mime: 'application/dssc+xml',
		name: 'Data Structure for the Security Suitability of Cryptographic Algorithms',
	},
	deb: { mime: 'application/x-debian-package', name: 'Debian Package' },
	uva: { mime: 'audio/vnd.dece.audio', name: 'DECE Audio' },
	uvi: { mime: 'image/vnd.dece.graphic', name: 'DECE Graphic' },
	uvh: { mime: 'video/vnd.dece.hd', name: 'DECE High Definition Video' },
	uvm: { mime: 'video/vnd.dece.mobile', name: 'DECE Mobile Video' },
	uvu: { mime: 'video/vnd.uvvu.mp4', name: 'DECE MP4' },
	uvp: { mime: 'video/vnd.dece.pd', name: 'DECE PD Video' },
	uvs: { mime: 'video/vnd.dece.sd', name: 'DECE SD Video' },
	uvv: { mime: 'video/vnd.dece.video', name: 'DECE Video' },
	dvi: { mime: 'application/x-dvi', name: 'Device Independent File Format (DVI)' },
	seed: {
		mime: 'application/vnd.fdsn.seed',
		name: 'Digital Siesmograph Networks - SEED Datafiles',
	},
	dtb: { mime: 'application/x-dtbook+xml', name: 'Digital Talking Book' },
	res: { mime: 'application/x-dtbresource+xml', name: 'Digital Talking Book - Resource File' },
	ait: { mime: 'application/vnd.dvb.ait', name: 'Digital Video Broadcasting' },
	svc: { mime: 'application/vnd.dvb.service', name: 'Digital Video Broadcasting' },
	eol: { mime: 'audio/vnd.digital-winds', name: 'Digital Winds Music' },
	djvu: { mime: 'image/vnd.djvu', name: 'DjVu' },
	dtd: { mime: 'application/xml-dtd', name: 'Document Type Definition' },
	mlp: { mime: 'application/vnd.dolby.mlp', name: 'Dolby Meridian Lossless Packing' },
	wad: { mime: 'application/x-doom', name: 'Doom Video Game' },
	dpg: { mime: 'application/vnd.dpgraph', name: 'DPGraph' },
	dra: { mime: 'audio/vnd.dra', name: 'DRA Audio' },
	dfac: { mime: 'application/vnd.dreamfactory', name: 'DreamFactory' },
	dts: { mime: 'audio/vnd.dts', name: 'DTS Audio' },
	dtshd: { mime: 'audio/vnd.dts.hd', name: 'DTS High Definition Audio' },
	dwg: { mime: 'image/vnd.dwg', name: 'DWG Drawing' },
	geo: { mime: 'application/vnd.dynageo', name: 'DynaGeo' },
	es: { mime: 'application/ecmascript', name: 'ECMAScript' },
	mag: { mime: 'application/vnd.ecowin.chart', name: 'EcoWin Chart' },
	mmr: { mime: 'image/vnd.fujixerox.edmics-mmr', name: 'EDMICS 2000' },
	rlc: { mime: 'image/vnd.fujixerox.edmics-rlc', name: 'EDMICS 2000' },
	exi: { mime: 'application/exi', name: 'Efficient XML Interchange' },
	mgz: { mime: 'application/vnd.proteus.magazine', name: 'EFI Proteus' },
	epub: { mime: 'application/epub+zip', name: 'Electronic Publication' },
	eml: { mime: 'message/rfc822', name: 'Email Message' },
	nml: { mime: 'application/vnd.enliven', name: 'Enliven Viewer' },
	xpr: { mime: 'application/vnd.is-xpr', name: 'Express by Infoseek' },
	xif: { mime: 'image/vnd.xiff', name: 'eXtended Image File Format (XIFF)' },
	xfdl: { mime: 'application/vnd.xfdl', name: 'Extensible Forms Description Language' },
	emma: { mime: 'application/emma+xml', name: 'Extensible MultiModal Annotation' },
	ez2: { mime: 'application/vnd.ezpix-album', name: 'EZPix Secure Photo Album' },
	ez3: { mime: 'application/vnd.ezpix-package', name: 'EZPix Secure Photo Album' },
	fst: { mime: 'image/vnd.fst', name: 'FAST Search & Transfer ASA' },
	fvt: { mime: 'video/vnd.fvt', name: 'FAST Search & Transfer ASA' },
	fbs: { mime: 'image/vnd.fastbidsheet', name: 'FastBid Sheet' },
	fe_launch: { mime: 'application/vnd.denovo.fcselayout-link', name: 'FCS Express Layout Link' },
	f4v: { mime: 'video/x-f4v', name: 'Flash Video' },
	flv: { mime: 'video/x-flv', name: 'Flash Video' },
	fpx: { mime: 'image/vnd.fpx', name: 'FlashPix' },
	npx: { mime: 'image/vnd.net-fpx', name: 'FlashPix' },
	flx: { mime: 'text/vnd.fmi.flexstor', name: 'FLEXSTOR' },
	fli: { mime: 'video/x-fli', name: 'FLI/FLC Animation Format' },
	ftc: { mime: 'application/vnd.fluxtime.clip', name: 'FluxTime Clip' },
	fdf: { mime: 'application/vnd.fdf', name: 'Forms Data Format' },
	f: { mime: 'text/x-fortran', name: 'Fortran Source File' },
	mif: { mime: 'application/vnd.mif', name: 'FrameMaker Interchange Format' },
	fm: { mime: 'application/vnd.framemaker', name: 'FrameMaker Normal Format' },
	fh: { mime: 'image/x-freehand', name: 'FreeHand MX' },
	fsc: { mime: 'application/vnd.fsc.weblaunch', name: 'Friendly Software Corporation' },
	fnc: { mime: 'application/vnd.frogans.fnc', name: 'Frogans Player' },
	ltf: { mime: 'application/vnd.frogans.ltf', name: 'Frogans Player' },
	ddd: { mime: 'application/vnd.fujixerox.ddd', name: 'Fujitsu - Xerox 2D CAD Data' },
	xdw: { mime: 'application/vnd.fujixerox.docuworks', name: 'Fujitsu - Xerox DocuWorks' },
	xbd: {
		mime: 'application/vnd.fujixerox.docuworks.binder',
		name: 'Fujitsu - Xerox DocuWorks Binder',
	},
	oas: { mime: 'application/vnd.fujitsu.oasys', name: 'Fujitsu Oasys' },
	oa2: { mime: 'application/vnd.fujitsu.oasys2', name: 'Fujitsu Oasys' },
	oa3: { mime: 'application/vnd.fujitsu.oasys3', name: 'Fujitsu Oasys' },
	fg5: { mime: 'application/vnd.fujitsu.oasysgp', name: 'Fujitsu Oasys' },
	bh2: { mime: 'application/vnd.fujitsu.oasysprs', name: 'Fujitsu Oasys' },
	spl: { mime: 'application/x-futuresplash', name: 'FutureSplash Animator' },
	fzs: { mime: 'application/vnd.fuzzysheet', name: 'FuzzySheet' },
	g3: { mime: 'image/g3fax', name: 'G3 Fax Image' },
	gmx: { mime: 'application/vnd.gmx', name: 'GameMaker ActiveX' },
	gtw: { mime: 'model/vnd.gtw', name: 'Gen-Trix Studio' },
	txd: { mime: 'application/vnd.genomatix.tuxedo', name: 'Genomatix Tuxedo Framework' },
	ggb: { mime: 'application/vnd.geogebra.file', name: 'GeoGebra' },
	ggt: { mime: 'application/vnd.geogebra.tool', name: 'GeoGebra' },
	gdl: { mime: 'model/vnd.gdl', name: 'Geometric Description Language (GDL)' },
	gex: { mime: 'application/vnd.geometry-explorer', name: 'GeoMetry Explorer' },
	gxt: { mime: 'application/vnd.geonext', name: 'GEONExT and JSXGraph' },
	g2w: { mime: 'application/vnd.geoplan', name: 'GeoplanW' },
	g3w: { mime: 'application/vnd.geospace', name: 'GeospacW' },
	gsf: { mime: 'application/x-font-ghostscript', name: 'Ghostscript Font' },
	bdf: { mime: 'application/x-font-bdf', name: 'Glyph Bitmap Distribution Format' },
	gtar: { mime: 'application/x-gtar', name: 'GNU Tar Files' },
	texinfo: { mime: 'application/x-texinfo', name: 'GNU Texinfo Document' },
	gnumeric: { mime: 'application/x-gnumeric', name: 'Gnumeric' },
	kml: { mime: 'application/vnd.google-earth.kml+xml', name: 'Google Earth - KML' },
	kmz: { mime: 'application/vnd.google-earth.kmz', name: 'Google Earth - Zipped KML' },
	gqf: { mime: 'application/vnd.grafeq', name: 'GrafEq' },
	gif: { mime: 'image/gif', name: 'Graphics Interchange Format' },
	gv: { mime: 'text/vnd.graphviz', name: 'Graphviz' },
	gac: { mime: 'application/vnd.groove-account', name: 'Groove - Account' },
	ghf: { mime: 'application/vnd.groove-help', name: 'Groove - Help' },
	gim: { mime: 'application/vnd.groove-identity-message', name: 'Groove - Identity Message' },
	grv: { mime: 'application/vnd.groove-injector', name: 'Groove - Injector' },
	gtm: { mime: 'application/vnd.groove-tool-message', name: 'Groove - Tool Message' },
	tpl: { mime: 'application/vnd.groove-tool-template', name: 'Groove - Tool Template' },
	vcg: { mime: 'application/vnd.groove-vcard', name: 'Groove - Vcard' },
	h261: { mime: 'video/h261', name: 'H.261' },
	h263: { mime: 'video/h263', name: 'H.263' },
	h264: { mime: 'video/h264', name: 'H.264' },
	hpid: { mime: 'application/vnd.hp-hpid', name: 'Hewlett Packard Instant Delivery' },
	hps: { mime: 'application/vnd.hp-hps', name: "Hewlett-Packard's WebPrintSmart" },
	hdf: { mime: 'application/x-hdf', name: 'Hierarchical Data Format' },
	rip: { mime: 'audio/vnd.rip', name: "Hit'n'Mix" },
	hbci: { mime: 'application/vnd.hbci', name: 'Homebanking Computer Interface (HBCI)' },
	jlt: { mime: 'application/vnd.hp-jlyt', name: 'HP Indigo Digital Press - Job Layout Languate' },
	pcl: { mime: 'application/vnd.hp-pcl', name: 'HP Printer Command Language' },
	hpgl: { mime: 'application/vnd.hp-hpgl', name: 'HP-GL/2 and HP RTL' },
	hvs: { mime: 'application/vnd.yamaha.hv-script', name: 'HV Script' },
	hvd: { mime: 'application/vnd.yamaha.hv-dic', name: 'HV Voice Dictionary' },
	hvp: { mime: 'application/vnd.yamaha.hv-voice', name: 'HV Voice Parameter' },
	'sfd-hdstx': { mime: 'application/vnd.hydrostatix.sof-data', name: 'Hydrostatix Master Suite' },
	stk: { mime: 'application/hyperstudio', name: 'Hyperstudio' },
	hal: { mime: 'application/vnd.hal+xml', name: 'Hypertext Application Language' },
	html: { mime: 'text/html', name: 'HyperText Markup Language (HTML)' },
	irm: { mime: 'application/vnd.ibm.rights-management', name: 'IBM DB2 Rights Manager' },
	sc: {
		mime: 'application/vnd.ibm.secure-container',
		name: 'IBM Electronic Media Management System - Secure Container',
	},
	ics: { mime: 'text/calendar', name: 'iCalendar' },
	icc: { mime: 'application/vnd.iccprofile', name: 'ICC profile' },
	ico: { mime: 'image/x-icon', name: 'Icon Image' },
	igl: { mime: 'application/vnd.igloader', name: 'igLoader' },
	ief: { mime: 'image/ief', name: 'Image Exchange Format' },
	ivp: { mime: 'application/vnd.immervision-ivp', name: 'ImmerVision PURE Players' },
	ivu: { mime: 'application/vnd.immervision-ivu', name: 'ImmerVision PURE Players' },
	rif: { mime: 'application/reginfo+xml', name: 'IMS Networks' },
	'3dml': { mime: 'text/vnd.in3d.3dml', name: 'In3D - 3DML' },
	spot: { mime: 'text/vnd.in3d.spot', name: 'In3D - 3DML' },
	igs: { mime: 'model/iges', name: 'Initial Graphics Exchange Specification (IGES)' },
	i2g: { mime: 'application/vnd.intergeo', name: 'Interactive Geometry Software' },
	cdy: { mime: 'application/vnd.cinderella', name: 'Interactive Geometry Software Cinderella' },
	xpw: { mime: 'application/vnd.intercon.formnet', name: 'Intercon FormNet' },
	fcs: {
		mime: 'application/vnd.isac.fcs',
		name: 'International Society for Advancement of Cytometry',
	},
	ipfix: { mime: 'application/ipfix', name: 'Internet Protocol Flow Information Export' },
	cer: { mime: 'application/pkix-cert', name: 'Internet Public Key Infrastructure - Certificate' },
	pki: {
		mime: 'application/pkixcmp',
		name: 'Internet Public Key Infrastructure - Certificate Management Protocole',
	},
	crl: {
		mime: 'application/pkix-crl',
		name: 'Internet Public Key Infrastructure - Certificate Revocation Lists',
	},
	pkipath: {
		mime: 'application/pkix-pkipath',
		name: 'Internet Public Key Infrastructure - Certification Path',
	},
	igm: { mime: 'application/vnd.insors.igm', name: 'IOCOM Visimeet' },
	rcprofile: { mime: 'application/vnd.ipunplugged.rcprofile', name: 'IP Unplugged Roaming Client' },
	irp: { mime: 'application/vnd.irepository.package+xml', name: 'iRepository / Lucidoc Editor' },
	jad: { mime: 'text/vnd.sun.j2me.app-descriptor', name: 'J2ME App Descriptor' },
	jar: { mime: 'application/java-archive', name: 'Java Archive' },
	class: { mime: 'application/java-vm', name: 'Java Bytecode File' },
	jnlp: { mime: 'application/x-java-jnlp-file', name: 'Java Network Launching Protocol' },
	ser: { mime: 'application/java-serialized-object', name: 'Java Serialized Object' },
	java: { mime: 'text/x-java-source,java', name: 'Java Source File' },
	js: { mime: 'application/javascript', name: 'JavaScript' },
	json: { mime: 'application/json', name: 'JavaScript Object Notation (JSON)' },
	joda: { mime: 'application/vnd.joost.joda-archive', name: 'Joda Archive' },
	jpm: { mime: 'video/jpm', name: 'JPEG 2000 Compound Image File Format' },
	jpeg: { mime: 'image/jpeg', name: 'JPEG Image' },
	jpg: { mime: 'image/jpeg', name: 'JPEG Image' },
	jpgv: { mime: 'video/jpeg', name: 'JPGVideo' },
	ktz: { mime: 'application/vnd.kahootz', name: 'Kahootz' },
	mmd: { mime: 'application/vnd.chipnuts.karaoke-mmd', name: 'Karaoke on Chipnuts Chipsets' },
	karbon: { mime: 'application/vnd.kde.karbon', name: 'KDE KOffice Office Suite - Karbon' },
	chrt: { mime: 'application/vnd.kde.kchart', name: 'KDE KOffice Office Suite - KChart' },
	kfo: { mime: 'application/vnd.kde.kformula', name: 'KDE KOffice Office Suite - Kformula' },
	flw: { mime: 'application/vnd.kde.kivio', name: 'KDE KOffice Office Suite - Kivio' },
	kon: { mime: 'application/vnd.kde.kontour', name: 'KDE KOffice Office Suite - Kontour' },
	kpr: { mime: 'application/vnd.kde.kpresenter', name: 'KDE KOffice Office Suite - Kpresenter' },
	ksp: { mime: 'application/vnd.kde.kspread', name: 'KDE KOffice Office Suite - Kspread' },
	kwd: { mime: 'application/vnd.kde.kword', name: 'KDE KOffice Office Suite - Kword' },
	htke: { mime: 'application/vnd.kenameaapp', name: 'Kenamea App' },
	kia: { mime: 'application/vnd.kidspiration', name: 'Kidspiration' },
	kne: { mime: 'application/vnd.kinar', name: 'Kinar Applications' },
	sse: { mime: 'application/vnd.kodak-descriptor', name: 'Kodak Storyshare' },
	lasxml: { mime: 'application/vnd.las.las+xml', name: 'Laser App Enterprise' },
	latex: { mime: 'application/x-latex', name: 'LaTeX' },
	lbd: {
		mime: 'application/vnd.llamagraphics.life-balance.desktop',
		name: 'Life Balance - Desktop Edition',
	},
	lbe: {
		mime: 'application/vnd.llamagraphics.life-balance.exchange+xml',
		name: 'Life Balance - Exchange Format',
	},
	jam: { mime: 'application/vnd.jam', name: 'Lightspeed Audio Lab' },
	'123': { mime: 'application/vnd.lotus-1-2-3', name: 'Lotus 1-2-3' },
	apr: { mime: 'application/vnd.lotus-approach', name: 'Lotus Approach' },
	pre: { mime: 'application/vnd.lotus-freelance', name: 'Lotus Freelance' },
	nsf: { mime: 'application/vnd.lotus-notes', name: 'Lotus Notes' },
	org: { mime: 'application/vnd.lotus-organizer', name: 'Lotus Organizer' },
	scm: { mime: 'application/vnd.lotus-screencam', name: 'Lotus Screencam' },
	lwp: { mime: 'application/vnd.lotus-wordpro', name: 'Lotus Wordpro' },
	lvp: { mime: 'audio/vnd.lucent.voice', name: 'Lucent Voice' },
	m3u: { mime: 'audio/x-mpegurl', name: 'M3U (Multimedia Playlist)' },
	m4v: { mime: 'video/x-m4v', name: 'M4v' },
	hqx: { mime: 'application/mac-binhex40', name: 'Macintosh BinHex 4.0' },
	portpkg: { mime: 'application/vnd.macports.portpkg', name: 'MacPorts Port System' },
	mgp: { mime: 'application/vnd.osgeo.mapguide.package', name: 'MapGuide DBXML' },
	mrc: { mime: 'application/marc', name: 'MARC Formats' },
	mrcx: { mime: 'application/marcxml+xml', name: 'MARC21 XML Schema' },
	mxf: { mime: 'application/mxf', name: 'Material Exchange Format' },
	nbp: { mime: 'application/vnd.wolfram.player', name: 'Mathematica Notebook Player' },
	ma: { mime: 'application/mathematica', name: 'Mathematica Notebooks' },
	mathml: { mime: 'application/mathml+xml', name: 'Mathematical Markup Language' },
	mbox: { mime: 'application/mbox', name: 'Mbox database files' },
	mc1: { mime: 'application/vnd.medcalcdata', name: 'MedCalc' },
	mscml: {
		mime: 'application/mediaservercontrol+xml',
		name: 'Media Server Control Markup Language',
	},
	cdkey: { mime: 'application/vnd.mediastation.cdkey', name: 'MediaRemote' },
	mwf: { mime: 'application/vnd.mfer', name: 'Medical Waveform Encoding Format' },
	mfm: { mime: 'application/vnd.mfmp', name: 'Melody Format for Mobile Platform' },
	msh: { mime: 'model/mesh', name: 'Mesh Data Type' },
	mads: { mime: 'application/mads+xml', name: 'Metadata Authority Description Schema' },
	mets: { mime: 'application/mets+xml', name: 'Metadata Encoding and Transmission Standard' },
	mods: { mime: 'application/mods+xml', name: 'Metadata Object Description Schema' },
	meta4: { mime: 'application/metalink4+xml', name: 'Metalink' },
	potm: {
		mime: 'application/vnd.ms-powerpoint.template.macroenabled.12',
		name: 'Micosoft PowerPoint - Macro-Enabled Template File',
	},
	docm: {
		mime: 'application/vnd.ms-word.document.macroenabled.12',
		name: 'Micosoft Word - Macro-Enabled Document',
	},
	dotm: {
		mime: 'application/vnd.ms-word.template.macroenabled.12',
		name: 'Micosoft Word - Macro-Enabled Template',
	},
	mcd: { mime: 'application/vnd.mcd', name: 'Micro CADAM Helix D&D' },
	flo: { mime: 'application/vnd.micrografx.flo', name: 'Micrografx' },
	igx: { mime: 'application/vnd.micrografx.igx', name: 'Micrografx iGrafx Professional' },
	es3: { mime: 'application/vnd.eszigno3+xml', name: 'MICROSEC e-Szign?' },
	mdb: { mime: 'application/x-msaccess', name: 'Microsoft Access' },
	asf: { mime: 'video/x-ms-asf', name: 'Microsoft Advanced Systems Format (ASF)' },
	exe: { mime: 'application/x-msdownload', name: 'Microsoft Application' },
	cil: { mime: 'application/vnd.ms-artgalry', name: 'Microsoft Artgalry' },
	cab: { mime: 'application/vnd.ms-cab-compressed', name: 'Microsoft Cabinet File' },
	ims: { mime: 'application/vnd.ms-ims', name: 'Microsoft Class Server' },
	application: { mime: 'application/x-ms-application', name: 'Microsoft ClickOnce' },
	clp: { mime: 'application/x-msclip', name: 'Microsoft Clipboard Clip' },
	mdi: { mime: 'image/vnd.ms-modi', name: 'Microsoft Document Imaging Format' },
	eot: { mime: 'application/vnd.ms-fontobject', name: 'Microsoft Embedded OpenType' },
	xls: { mime: 'application/vnd.ms-excel', name: 'Microsoft Excel' },
	xlam: {
		mime: 'application/vnd.ms-excel.addin.macroenabled.12',
		name: 'Microsoft Excel - Add-In File',
	},
	xlsb: {
		mime: 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
		name: 'Microsoft Excel - Binary Workbook',
	},
	xltm: {
		mime: 'application/vnd.ms-excel.template.macroenabled.12',
		name: 'Microsoft Excel - Macro-Enabled Template File',
	},
	xlsm: {
		mime: 'application/vnd.ms-excel.sheet.macroenabled.12',
		name: 'Microsoft Excel - Macro-Enabled Workbook',
	},
	chm: { mime: 'application/vnd.ms-htmlhelp', name: 'Microsoft Html Help File' },
	crd: { mime: 'application/x-mscardfile', name: 'Microsoft Information Card' },
	lrm: { mime: 'application/vnd.ms-lrm', name: 'Microsoft Learning Resource Module' },
	mvb: { mime: 'application/x-msmediaview', name: 'Microsoft MediaView' },
	mny: { mime: 'application/x-msmoney', name: 'Microsoft Money' },
	pptx: {
		mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		name: 'Microsoft Office - OOXML - Presentation',
	},
	sldx: {
		mime: 'application/vnd.openxmlformats-officedocument.presentationml.slide',
		name: 'Microsoft Office - OOXML - Presentation (Slide)',
	},
	ppsx: {
		mime: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
		name: 'Microsoft Office - OOXML - Presentation (Slideshow)',
	},
	potx: {
		mime: 'application/vnd.openxmlformats-officedocument.presentationml.template',
		name: 'Microsoft Office - OOXML - Presentation Template',
	},
	xlsx: {
		mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
		name: 'Microsoft Office - OOXML - Spreadsheet',
	},
	xltx: {
		mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
		name: 'Microsoft Office - OOXML - Spreadsheet Teplate',
	},
	docx: {
		mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		name: 'Microsoft Office - OOXML - Word Document',
	},
	dotx: {
		mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
		name: 'Microsoft Office - OOXML - Word Document Template',
	},
	obd: { mime: 'application/x-msbinder', name: 'Microsoft Office Binder' },
	thmx: { mime: 'application/vnd.ms-officetheme', name: 'Microsoft Office System Release Theme' },
	onetoc: { mime: 'application/onenote', name: 'Microsoft OneNote' },
	pya: { mime: 'audio/vnd.ms-playready.media.pya', name: 'Microsoft PlayReady Ecosystem' },
	pyv: { mime: 'video/vnd.ms-playready.media.pyv', name: 'Microsoft PlayReady Ecosystem Video' },
	ppt: { mime: 'application/vnd.ms-powerpoint', name: 'Microsoft PowerPoint' },
	ppam: {
		mime: 'application/vnd.ms-powerpoint.addin.macroenabled.12',
		name: 'Microsoft PowerPoint - Add-in file',
	},
	sldm: {
		mime: 'application/vnd.ms-powerpoint.slide.macroenabled.12',
		name: 'Microsoft PowerPoint - Macro-Enabled Open XML Slide',
	},
	pptm: {
		mime: 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
		name: 'Microsoft PowerPoint - Macro-Enabled Presentation File',
	},
	ppsm: {
		mime: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
		name: 'Microsoft PowerPoint - Macro-Enabled Slide Show File',
	},
	mpp: { mime: 'application/vnd.ms-project', name: 'Microsoft Project' },
	pub: { mime: 'application/x-mspublisher', name: 'Microsoft Publisher' },
	scd: { mime: 'application/x-msschedule', name: 'Microsoft Schedule+' },
	xap: { mime: 'application/x-silverlight-app', name: 'Microsoft Silverlight' },
	stl: {
		mime: 'application/vnd.ms-pki.stl',
		name: 'Microsoft Trust UI Provider - Certificate Trust Link',
	},
	cat: {
		mime: 'application/vnd.ms-pki.seccat',
		name: 'Microsoft Trust UI Provider - Security Catalog',
	},
	vsd: { mime: 'application/vnd.visio', name: 'Microsoft Visio' },
	wm: { mime: 'video/x-ms-wm', name: 'Microsoft Windows Media' },
	wma: { mime: 'audio/x-ms-wma', name: 'Microsoft Windows Media Audio' },
	wax: { mime: 'audio/x-ms-wax', name: 'Microsoft Windows Media Audio Redirector' },
	wmx: { mime: 'video/x-ms-wmx', name: 'Microsoft Windows Media Audio/Video Playlist' },
	wmd: { mime: 'application/x-ms-wmd', name: 'Microsoft Windows Media Player Download Package' },
	wpl: { mime: 'application/vnd.ms-wpl', name: 'Microsoft Windows Media Player Playlist' },
	wmz: { mime: 'application/x-ms-wmz', name: 'Microsoft Windows Media Player Skin Package' },
	wmv: { mime: 'video/x-ms-wmv', name: 'Microsoft Windows Media Video' },
	wvx: { mime: 'video/x-ms-wvx', name: 'Microsoft Windows Media Video Playlist' },
	wmf: { mime: 'application/x-msmetafile', name: 'Microsoft Windows Metafile' },
	trm: { mime: 'application/x-msterminal', name: 'Microsoft Windows Terminal Services' },
	doc: { mime: 'application/msword', name: 'Microsoft Word' },
	wri: { mime: 'application/x-mswrite', name: 'Microsoft Wordpad' },
	wps: { mime: 'application/vnd.ms-works', name: 'Microsoft Works' },
	xbap: { mime: 'application/x-ms-xbap', name: 'Microsoft XAML Browser Application' },
	xps: { mime: 'application/vnd.ms-xpsdocument', name: 'Microsoft XML Paper Specification' },
	mid: { mime: 'audio/midi', name: 'MIDI - Musical Instrument Digital Interface' },
	mpy: { mime: 'application/vnd.ibm.minipay', name: 'MiniPay' },
	afp: { mime: 'application/vnd.ibm.modcap', name: 'MO:DCA-P' },
	rms: { mime: 'application/vnd.jcp.javame.midlet-rms', name: 'Mobile Information Device Profile' },
	tmo: { mime: 'application/vnd.tmobile-livetv', name: 'MobileTV' },
	prc: { mime: 'application/x-mobipocket-ebook', name: 'Mobipocket' },
	mbk: { mime: 'application/vnd.mobius.mbk', name: 'Mobius Management Systems - Basket file' },
	dis: {
		mime: 'application/vnd.mobius.dis',
		name: 'Mobius Management Systems - Distribution Database',
	},
	plc: {
		mime: 'application/vnd.mobius.plc',
		name: 'Mobius Management Systems - Policy Definition Language File',
	},
	mqy: { mime: 'application/vnd.mobius.mqy', name: 'Mobius Management Systems - Query File' },
	msl: { mime: 'application/vnd.mobius.msl', name: 'Mobius Management Systems - Script Language' },
	txf: { mime: 'application/vnd.mobius.txf', name: 'Mobius Management Systems - Topic Index File' },
	daf: { mime: 'application/vnd.mobius.daf', name: 'Mobius Management Systems - UniversalArchive' },
	fly: { mime: 'text/vnd.fly', name: 'mod_fly / fly.cgi' },
	mpc: { mime: 'application/vnd.mophun.certificate', name: 'Mophun Certificate' },
	mpn: { mime: 'application/vnd.mophun.application', name: 'Mophun VM' },
	mj2: { mime: 'video/mj2', name: 'Motion JPEG 2000' },
	mpga: { mime: 'audio/mpeg', name: 'MPEG Audio' },
	mxu: { mime: 'video/vnd.mpegurl', name: 'MPEG Url' },
	mpeg: { mime: 'video/mpeg', name: 'MPEG Video' },
	m21: { mime: 'application/mp21', name: 'MPEG-21' },
	mp4a: { mime: 'audio/mp4', name: 'MPEG-4 Audio' },
	mp4: { mime: 'video/mp4', name: 'MPEG-4 Video' },
	m3u8: { mime: 'application/vnd.apple.mpegurl', name: 'Multimedia Playlist Unicode' },
	mus: {
		mime: 'application/vnd.musician',
		name: 'MUsical Score Interpreted Code Invented for the ASCII designation of Notation',
	},
	msty: { mime: 'application/vnd.muvee.style', name: 'Muvee Automatic Video Editing' },
	mxml: { mime: 'application/xv+xml', name: 'MXML' },
	ngdat: { mime: 'application/vnd.nokia.n-gage.data', name: 'N-Gage Game Data' },
	'n-gage': { mime: 'application/vnd.nokia.n-gage.symbian.install', name: 'N-Gage Game Installer' },
	ncx: { mime: 'application/x-dtbncx+xml', name: 'Navigation Control file for XML (for ePub)' },
	nc: { mime: 'application/x-netcdf', name: 'Network Common Data Form (NetCDF)' },
	nlu: { mime: 'application/vnd.neurolanguage.nlu', name: 'neuroLanguage' },
	dna: { mime: 'application/vnd.dna', name: 'New Moon Liftoff/DNA' },
	nnd: { mime: 'application/vnd.noblenet-directory', name: 'NobleNet Directory' },
	nns: { mime: 'application/vnd.noblenet-sealer', name: 'NobleNet Sealer' },
	nnw: { mime: 'application/vnd.noblenet-web', name: 'NobleNet Web' },
	rpst: { mime: 'application/vnd.nokia.radio-preset', name: 'Nokia Radio Application - Preset' },
	rpss: { mime: 'application/vnd.nokia.radio-presets', name: 'Nokia Radio Application - Preset' },
	n3: { mime: 'text/n3', name: 'Notation3' },
	edm: { mime: 'application/vnd.novadigm.edm', name: "Novadigm's RADIA and EDM products" },
	edx: { mime: 'application/vnd.novadigm.edx', name: "Novadigm's RADIA and EDM products" },
	ext: { mime: 'application/vnd.novadigm.ext', name: "Novadigm's RADIA and EDM products" },
	gph: { mime: 'application/vnd.flographit', name: 'NpGraphIt' },
	ecelp4800: { mime: 'audio/vnd.nuera.ecelp4800', name: 'Nuera ECELP 4800' },
	ecelp7470: { mime: 'audio/vnd.nuera.ecelp7470', name: 'Nuera ECELP 7470' },
	ecelp9600: { mime: 'audio/vnd.nuera.ecelp9600', name: 'Nuera ECELP 9600' },
	oda: { mime: 'application/oda', name: 'Office Document Architecture' },
	ogx: { mime: 'application/ogg', name: 'Ogg' },
	oga: { mime: 'audio/ogg', name: 'Ogg Audio' },
	ogv: { mime: 'video/ogg', name: 'Ogg Video' },
	dd2: { mime: 'application/vnd.oma.dd2+xml', name: 'OMA Download Agents' },
	oth: { mime: 'application/vnd.oasis.opendocument.text-web', name: 'Open Document Text Web' },
	opf: { mime: 'application/oebps-package+xml', name: 'Open eBook Publication Structure' },
	qbo: { mime: 'application/vnd.intu.qbo', name: 'Open Financial Exchange' },
	oxt: { mime: 'application/vnd.openofficeorg.extension', name: 'Open Office Extension' },
	osf: { mime: 'application/vnd.yamaha.openscoreformat', name: 'Open Score Format' },
	weba: { mime: 'audio/webm', name: 'Open Web Media Project - Audio' },
	webm: { mime: 'video/webm', name: 'Open Web Media Project - Video' },
	odc: { mime: 'application/vnd.oasis.opendocument.chart', name: 'OpenDocument Chart' },
	otc: {
		mime: 'application/vnd.oasis.opendocument.chart-template',
		name: 'OpenDocument Chart Template',
	},
	odb: { mime: 'application/vnd.oasis.opendocument.database', name: 'OpenDocument Database' },
	odf: { mime: 'application/vnd.oasis.opendocument.formula', name: 'OpenDocument Formula' },
	odft: {
		mime: 'application/vnd.oasis.opendocument.formula-template',
		name: 'OpenDocument Formula Template',
	},
	odg: { mime: 'application/vnd.oasis.opendocument.graphics', name: 'OpenDocument Graphics' },
	otg: {
		mime: 'application/vnd.oasis.opendocument.graphics-template',
		name: 'OpenDocument Graphics Template',
	},
	odi: { mime: 'application/vnd.oasis.opendocument.image', name: 'OpenDocument Image' },
	oti: {
		mime: 'application/vnd.oasis.opendocument.image-template',
		name: 'OpenDocument Image Template',
	},
	odp: {
		mime: 'application/vnd.oasis.opendocument.presentation',
		name: 'OpenDocument Presentation',
	},
	otp: {
		mime: 'application/vnd.oasis.opendocument.presentation-template',
		name: 'OpenDocument Presentation Template',
	},
	ods: { mime: 'application/vnd.oasis.opendocument.spreadsheet', name: 'OpenDocument Spreadsheet' },
	ots: {
		mime: 'application/vnd.oasis.opendocument.spreadsheet-template',
		name: 'OpenDocument Spreadsheet Template',
	},
	odt: { mime: 'application/vnd.oasis.opendocument.text', name: 'OpenDocument Text' },
	odm: { mime: 'application/vnd.oasis.opendocument.text-master', name: 'OpenDocument Text Master' },
	ott: {
		mime: 'application/vnd.oasis.opendocument.text-template',
		name: 'OpenDocument Text Template',
	},
	ktx: { mime: 'image/ktx', name: 'OpenGL Textures (KTX)' },
	sxc: { mime: 'application/vnd.sun.xml.calc', name: 'OpenOffice - Calc (Spreadsheet)' },
	stc: {
		mime: 'application/vnd.sun.xml.calc.template',
		name: 'OpenOffice - Calc Template (Spreadsheet)',
	},
	sxd: { mime: 'application/vnd.sun.xml.draw', name: 'OpenOffice - Draw (Graphics)' },
	std: {
		mime: 'application/vnd.sun.xml.draw.template',
		name: 'OpenOffice - Draw Template (Graphics)',
	},
	sxi: { mime: 'application/vnd.sun.xml.impress', name: 'OpenOffice - Impress (Presentation)' },
	sti: {
		mime: 'application/vnd.sun.xml.impress.template',
		name: 'OpenOffice - Impress Template (Presentation)',
	},
	sxm: { mime: 'application/vnd.sun.xml.math', name: 'OpenOffice - Math (Formula)' },
	sxw: { mime: 'application/vnd.sun.xml.writer', name: 'OpenOffice - Writer (Text - HTML)' },
	sxg: { mime: 'application/vnd.sun.xml.writer.global', name: 'OpenOffice - Writer (Text - HTML)' },
	stw: {
		mime: 'application/vnd.sun.xml.writer.template',
		name: 'OpenOffice - Writer Template (Text - HTML)',
	},
	otf: { mime: 'application/x-font-otf', name: 'OpenType Font File' },
	osfpvg: { mime: 'application/vnd.yamaha.openscoreformat.osfpvg+xml', name: 'OSFPVG' },
	dp: { mime: 'application/vnd.osgi.dp', name: 'OSGi Deployment Package' },
	pdb: { mime: 'application/vnd.palm', name: 'PalmOS Data' },
	p: { mime: 'text/x-pascal', name: 'Pascal Source File' },
	paw: { mime: 'application/vnd.pawaafile', name: 'PawaaFILE' },
	pclxl: { mime: 'application/vnd.hp-pclxl', name: 'PCL 6 Enhanced (Formely PCL XL)' },
	efif: { mime: 'application/vnd.picsel', name: 'Pcsel eFIF File' },
	pcx: { mime: 'image/x-pcx', name: 'PCX Image' },
	psd: { mime: 'image/vnd.adobe.photoshop', name: 'Photoshop Document' },
	prf: { mime: 'application/pics-rules', name: 'PICSRules' },
	pic: { mime: 'image/x-pict', name: 'PICT Image' },
	chat: { mime: 'application/x-chat', name: 'pIRCh' },
	p10: { mime: 'application/pkcs10', name: 'PKCS #10 - Certification Request Standard' },
	p12: {
		mime: 'application/x-pkcs12',
		name: 'PKCS #12 - Personal Information Exchange Syntax Standard',
	},
	p7m: { mime: 'application/pkcs7-mime', name: 'PKCS #7 - Cryptographic Message Syntax Standard' },
	p7s: {
		mime: 'application/pkcs7-signature',
		name: 'PKCS #7 - Cryptographic Message Syntax Standard',
	},
	p7r: {
		mime: 'application/x-pkcs7-certreqresp',
		name: 'PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)',
	},
	p7b: {
		mime: 'application/x-pkcs7-certificates',
		name: 'PKCS #7 - Cryptographic Message Syntax Standard (Certificates)',
	},
	p8: { mime: 'application/pkcs8', name: 'PKCS #8 - Private-Key Information Syntax Standard' },
	plf: { mime: 'application/vnd.pocketlearn', name: 'PocketLearn Viewers' },
	pnm: { mime: 'image/x-portable-anymap', name: 'Portable Anymap Image' },
	pbm: { mime: 'image/x-portable-bitmap', name: 'Portable Bitmap Format' },
	pcf: { mime: 'application/x-font-pcf', name: 'Portable Compiled Format' },
	pfr: { mime: 'application/font-tdpfr', name: 'Portable Font Resource' },
	pgn: { mime: 'application/x-chess-pgn', name: 'Portable Game Notation (Chess Games)' },
	pgm: { mime: 'image/x-portable-graymap', name: 'Portable Graymap Format' },
	png: { mime: 'image/png', name: 'Portable Network Graphics (PNG)' },
	ppm: { mime: 'image/x-portable-pixmap', name: 'Portable Pixmap Format' },
	pskcxml: { mime: 'application/pskc+xml', name: 'Portable Symmetric Key Container' },
	pml: { mime: 'application/vnd.ctc-posml', name: 'PosML' },
	ai: { mime: 'application/postscript', name: 'PostScript' },
	pfa: { mime: 'application/x-font-type1', name: 'PostScript Fonts' },
	pbd: { mime: 'application/vnd.powerbuilder6', name: 'PowerBuilder' },
	pgp: { mime: 'application/pgp-signature', name: 'Pretty Good Privacy - Signature' },
	box: { mime: 'application/vnd.previewsystems.box', name: 'Preview Systems ZipLock/VBox' },
	ptid: { mime: 'application/vnd.pvi.ptid1', name: 'Princeton Video Image' },
	pls: { mime: 'application/pls+xml', name: 'Pronunciation Lexicon Specification' },
	str: { mime: 'application/vnd.pg.format', name: 'Proprietary P&G Standard Reporting System' },
	ei6: { mime: 'application/vnd.pg.osasli', name: 'Proprietary P&G Standard Reporting System' },
	dsc: { mime: 'text/prs.lines.tag', name: 'PRS Lines Tag' },
	psf: { mime: 'application/x-font-linux-psf', name: 'PSF Fonts' },
	qps: { mime: 'application/vnd.publishare-delta-tree', name: 'PubliShare Objects' },
	wg: { mime: 'application/vnd.pmi.widget', name: "Qualcomm's Plaza Mobile Internet" },
	qxd: { mime: 'application/vnd.quark.quarkxpress', name: 'QuarkXpress' },
	esf: { mime: 'application/vnd.epson.esf', name: 'QUASS Stream Player' },
	msf: { mime: 'application/vnd.epson.msf', name: 'QUASS Stream Player' },
	ssf: { mime: 'application/vnd.epson.ssf', name: 'QUASS Stream Player' },
	qam: { mime: 'application/vnd.epson.quickanime', name: 'QuickAnime Player' },
	qfx: { mime: 'application/vnd.intu.qfx', name: 'Quicken' },
	qt: { mime: 'video/quicktime', name: 'Quicktime Video' },
	rar: { mime: 'application/x-rar-compressed', name: 'RAR Archive' },
	ram: { mime: 'audio/x-pn-realaudio', name: 'Real Audio Sound' },
	rmp: { mime: 'audio/x-pn-realaudio-plugin', name: 'Real Audio Sound' },
	rsd: { mime: 'application/rsd+xml', name: 'Really Simple Discovery' },
	rm: { mime: 'application/vnd.rn-realmedia', name: 'RealMedia' },
	bed: { mime: 'application/vnd.realvnc.bed', name: 'RealVNC' },
	mxl: { mime: 'application/vnd.recordare.musicxml', name: 'Recordare Applications' },
	musicxml: { mime: 'application/vnd.recordare.musicxml+xml', name: 'Recordare Applications' },
	rnc: { mime: 'application/relax-ng-compact-syntax', name: 'Relax NG Compact Syntax' },
	rdz: { mime: 'application/vnd.data-vision.rdz', name: 'RemoteDocs R-Viewer' },
	rdf: { mime: 'application/rdf+xml', name: 'Resource Description Framework' },
	rp9: { mime: 'application/vnd.cloanto.rp9', name: 'RetroPlatform Player' },
	jisp: { mime: 'application/vnd.jisp', name: 'RhymBox' },
	rtf: { mime: 'application/rtf', name: 'Rich Text Format' },
	rtx: { mime: 'text/richtext', name: 'Rich Text Format (RTF)' },
	link66: { mime: 'application/vnd.route66.link66+xml', name: 'ROUTE 66 Location Based Services' },
	'rss, .xml': { mime: 'application/rss+xml', name: 'RSS - Really Simple Syndication' },
	shf: { mime: 'application/shf+xml', name: 'S Hexdump Format' },
	st: { mime: 'application/vnd.sailingtracker.track', name: 'SailingTracker' },
	svg: { mime: 'image/svg+xml', name: 'Scalable Vector Graphics (SVG)' },
	sus: { mime: 'application/vnd.sus-calendar', name: 'ScheduleUs' },
	sru: { mime: 'application/sru+xml', name: 'Search/Retrieve via URL Response Format' },
	setpay: {
		mime: 'application/set-payment-initiation',
		name: 'Secure Electronic Transaction - Payment',
	},
	setreg: {
		mime: 'application/set-registration-initiation',
		name: 'Secure Electronic Transaction - Registration',
	},
	sema: { mime: 'application/vnd.sema', name: 'Secured eMail' },
	semd: { mime: 'application/vnd.semd', name: 'Secured eMail' },
	semf: { mime: 'application/vnd.semf', name: 'Secured eMail' },
	see: { mime: 'application/vnd.seemail', name: 'SeeMail' },
	snf: { mime: 'application/x-font-snf', name: 'Server Normal Format' },
	spq: {
		mime: 'application/scvp-vp-request',
		name: 'Server-Based Certificate Validation Protocol - Validation Policies - Request',
	},
	spp: {
		mime: 'application/scvp-vp-response',
		name: 'Server-Based Certificate Validation Protocol - Validation Policies - Response',
	},
	scq: {
		mime: 'application/scvp-cv-request',
		name: 'Server-Based Certificate Validation Protocol - Validation Request',
	},
	scs: {
		mime: 'application/scvp-cv-response',
		name: 'Server-Based Certificate Validation Protocol - Validation Response',
	},
	sdp: { mime: 'application/sdp', name: 'Session Description Protocol' },
	etx: { mime: 'text/x-setext', name: 'Setext' },
	movie: { mime: 'video/x-sgi-movie', name: 'SGI Movie' },
	ifm: { mime: 'application/vnd.shana.informed.formdata', name: 'Shana Informed Filler' },
	itp: { mime: 'application/vnd.shana.informed.formtemplate', name: 'Shana Informed Filler' },
	iif: { mime: 'application/vnd.shana.informed.interchange', name: 'Shana Informed Filler' },
	ipk: { mime: 'application/vnd.shana.informed.package', name: 'Shana Informed Filler' },
	tfi: { mime: 'application/thraud+xml', name: 'Sharing Transaction Fraud Data' },
	shar: { mime: 'application/x-shar', name: 'Shell Archive' },
	rgb: { mime: 'image/x-rgb', name: 'Silicon Graphics RGB Bitmap' },
	slt: { mime: 'application/vnd.epson.salt', name: 'SimpleAnimeLite Player' },
	aso: { mime: 'application/vnd.accpac.simply.aso', name: 'Simply Accounting' },
	imp: { mime: 'application/vnd.accpac.simply.imp', name: 'Simply Accounting - Data Import' },
	twd: { mime: 'application/vnd.simtech-mindmapper', name: 'SimTech MindMapper' },
	csp: { mime: 'application/vnd.commonspace', name: 'Sixth Floor Media - CommonSpace' },
	saf: { mime: 'application/vnd.yamaha.smaf-audio', name: 'SMAF Audio' },
	mmf: { mime: 'application/vnd.smaf', name: 'SMAF File' },
	spf: { mime: 'application/vnd.yamaha.smaf-phrase', name: 'SMAF Phrase' },
	teacher: { mime: 'application/vnd.smart.teacher', name: 'SMART Technologies Apps' },
	svd: { mime: 'application/vnd.svd', name: 'SourceView Document' },
	rq: { mime: 'application/sparql-query', name: 'SPARQL - Query' },
	srx: { mime: 'application/sparql-results+xml', name: 'SPARQL - Results' },
	gram: { mime: 'application/srgs', name: 'Speech Recognition Grammar Specification' },
	grxml: { mime: 'application/srgs+xml', name: 'Speech Recognition Grammar Specification - XML' },
	ssml: { mime: 'application/ssml+xml', name: 'Speech Synthesis Markup Language' },
	skp: { mime: 'application/vnd.koan', name: 'SSEYO Koan Play File' },
	sgml: { mime: 'text/sgml', name: 'Standard Generalized Markup Language (SGML)' },
	sdc: { mime: 'application/vnd.stardivision.calc', name: 'StarOffice - Calc' },
	sda: { mime: 'application/vnd.stardivision.draw', name: 'StarOffice - Draw' },
	sdd: { mime: 'application/vnd.stardivision.impress', name: 'StarOffice - Impress' },
	smf: { mime: 'application/vnd.stardivision.math', name: 'StarOffice - Math' },
	sdw: { mime: 'application/vnd.stardivision.writer', name: 'StarOffice - Writer' },
	sgl: { mime: 'application/vnd.stardivision.writer-global', name: 'StarOffice - Writer (Global)' },
	sm: { mime: 'application/vnd.stepmania.stepchart', name: 'StepMania' },
	sit: { mime: 'application/x-stuffit', name: 'Stuffit Archive' },
	sitx: { mime: 'application/x-stuffitx', name: 'Stuffit Archive' },
	sdkm: { mime: 'application/vnd.solent.sdkm+xml', name: 'SudokuMagic' },
	xo: { mime: 'application/vnd.olpc-sugar', name: 'Sugar Linux Application Bundle' },
	au: { mime: 'audio/basic', name: 'Sun Audio - Au file format' },
	wqd: { mime: 'application/vnd.wqd', name: 'SundaHus WQ' },
	sis: { mime: 'application/vnd.symbian.install', name: 'Symbian Install Package' },
	smi: { mime: 'application/smil+xml', name: 'Synchronized Multimedia Integration Language' },
	xsm: { mime: 'application/vnd.syncml+xml', name: 'SyncML' },
	bdm: { mime: 'application/vnd.syncml.dm+wbxml', name: 'SyncML - Device Management' },
	xdm: { mime: 'application/vnd.syncml.dm+xml', name: 'SyncML - Device Management' },
	sv4cpio: { mime: 'application/x-sv4cpio', name: 'System V Release 4 CPIO Archive' },
	sv4crc: { mime: 'application/x-sv4crc', name: 'System V Release 4 CPIO Checksum Data' },
	sbml: { mime: 'application/sbml+xml', name: 'Systems Biology Markup Language' },
	tsv: { mime: 'text/tab-separated-values', name: 'Tab Seperated Values' },
	tiff: { mime: 'image/tiff', name: 'Tagged Image File Format' },
	tao: { mime: 'application/vnd.tao.intent-module-archive', name: 'Tao Intent' },
	tar: { mime: 'application/x-tar', name: 'Tar File (Tape Archive)' },
	tcl: { mime: 'application/x-tcl', name: 'Tcl Script' },
	tex: { mime: 'application/x-tex', name: 'TeX' },
	tfm: { mime: 'application/x-tex-tfm', name: 'TeX Font Metric' },
	tei: { mime: 'application/tei+xml', name: 'Text Encoding and Interchange' },
	txt: { mime: 'text/plain', name: 'Text File' },
	dxp: { mime: 'application/vnd.spotfire.dxp', name: 'TIBCO Spotfire' },
	sfs: { mime: 'application/vnd.spotfire.sfs', name: 'TIBCO Spotfire' },
	tsd: { mime: 'application/timestamped-data', name: 'Time Stamped Data Envelope' },
	tpt: { mime: 'application/vnd.trid.tpt', name: 'TRI Systems Config' },
	mxs: { mime: 'application/vnd.triscape.mxs', name: 'Triscape Map Explorer' },
	t: { mime: 'text/troff', name: 'troff' },
	tra: { mime: 'application/vnd.trueapp', name: 'True BASIC' },
	ttf: { mime: 'application/x-font-ttf', name: 'TrueType Font' },
	ttl: { mime: 'text/turtle', name: 'Turtle (Terse RDF Triple Language)' },
	umj: { mime: 'application/vnd.umajin', name: 'UMAJIN' },
	uoml: { mime: 'application/vnd.uoml+xml', name: 'Unique Object Markup Language' },
	unityweb: { mime: 'application/vnd.unity', name: 'Unity 3d' },
	ufd: { mime: 'application/vnd.ufdl', name: 'Universal Forms Description Language' },
	uri: { mime: 'text/uri-list', name: 'URI Resolution Services' },
	utz: { mime: 'application/vnd.uiq.theme', name: 'User Interface Quartz - Theme (Symbian)' },
	ustar: { mime: 'application/x-ustar', name: 'Ustar (Uniform Standard Tape Archive)' },
	uu: { mime: 'text/x-uuencode', name: 'UUEncode' },
	vcs: { mime: 'text/x-vcalendar', name: 'vCalendar' },
	vcf: { mime: 'text/x-vcard', name: 'vCard' },
	vcd: { mime: 'application/x-cdlink', name: 'Video CD' },
	vsf: { mime: 'application/vnd.vsf', name: 'Viewport+' },
	wrl: { mime: 'model/vrml', name: 'Virtual Reality Modeling Language' },
	vcx: { mime: 'application/vnd.vcx', name: 'VirtualCatalog' },
	mts: { mime: 'model/vnd.mts', name: 'Virtue MTS' },
	vtu: { mime: 'model/vnd.vtu', name: 'Virtue VTU' },
	vis: { mime: 'application/vnd.visionary', name: 'Visionary' },
	viv: { mime: 'video/vnd.vivo', name: 'Vivo' },
	ccxml: { mime: 'application/ccxml+xml,', name: 'Voice Browser Call Control' },
	vxml: { mime: 'application/voicexml+xml', name: 'VoiceXML' },
	src: { mime: 'application/x-wais-source', name: 'WAIS Source' },
	wbxml: { mime: 'application/vnd.wap.wbxml', name: 'WAP Binary XML (WBXML)' },
	wbmp: { mime: 'image/vnd.wap.wbmp', name: 'WAP Bitamp (WBMP)' },
	wav: { mime: 'audio/x-wav', name: 'Waveform Audio File Format (WAV)' },
	davmount: { mime: 'application/davmount+xml', name: 'Web Distributed Authoring and Versioning' },
	woff: { mime: 'application/x-font-woff', name: 'Web Open Font Format' },
	wspolicy: { mime: 'application/wspolicy+xml', name: 'Web Services Policy' },
	webp: { mime: 'image/webp', name: 'WebP Image' },
	wtb: { mime: 'application/vnd.webturbo', name: 'WebTurbo' },
	wgt: { mime: 'application/widget', name: 'Widget Packaging and XML Configuration' },
	hlp: { mime: 'application/winhlp', name: 'WinHelp' },
	wml: { mime: 'text/vnd.wap.wml', name: 'Wireless Markup Language (WML)' },
	wmls: { mime: 'text/vnd.wap.wmlscript', name: 'Wireless Markup Language Script (WMLScript)' },
	wmlsc: { mime: 'application/vnd.wap.wmlscriptc', name: 'WMLScript' },
	wpd: { mime: 'application/vnd.wordperfect', name: 'Wordperfect' },
	stf: { mime: 'application/vnd.wt.stf', name: 'Worldtalk' },
	wsdl: { mime: 'application/wsdl+xml', name: 'WSDL - Web Services Description Language' },
	xbm: { mime: 'image/x-xbitmap', name: 'X BitMap' },
	xpm: { mime: 'image/x-xpixmap', name: 'X PixMap' },
	xwd: { mime: 'image/x-xwindowdump', name: 'X Window Dump' },
	der: { mime: 'application/x-x509-ca-cert', name: 'X.509 Certificate' },
	fig: { mime: 'application/x-xfig', name: 'Xfig' },
	xhtml: {
		mime: 'application/xhtml+xml',
		name: 'XHTML - The Extensible HyperText Markup Language',
	},
	xml: { mime: 'application/xml', name: 'XML - Extensible Markup Language' },
	xdf: { mime: 'application/xcap-diff+xml', name: 'XML Configuration Access Protocol - XCAP Diff' },
	xenc: { mime: 'application/xenc+xml', name: 'XML Encryption Syntax and Processing' },
	xer: { mime: 'application/patch-ops-error+xml', name: 'XML Patch Framework' },
	rl: { mime: 'application/resource-lists+xml', name: 'XML Resource Lists' },
	rs: { mime: 'application/rls-services+xml', name: 'XML Resource Lists' },
	rld: { mime: 'application/resource-lists-diff+xml', name: 'XML Resource Lists Diff' },
	xslt: { mime: 'application/xslt+xml', name: 'XML Transformations' },
	xop: { mime: 'application/xop+xml', name: 'XML-Binary Optimized Packaging' },
	xpi: { mime: 'application/x-xpinstall', name: 'XPInstall - Mozilla' },
	xspf: { mime: 'application/xspf+xml', name: 'XSPF - XML Shareable Playlist Format' },
	xul: { mime: 'application/vnd.mozilla.xul+xml', name: 'XUL - XML User Interface Language' },
	xyz: { mime: 'chemical/x-xyz', name: 'XYZ File Format' },
	yaml: { mime: 'text/yaml', name: "YAML Ain't Markup Language / Yet Another Markup Language" },
	yang: { mime: 'application/yang', name: 'YANG Data Modeling Language' },
	yin: { mime: 'application/yin+xml', name: 'YIN (YANG - XML)' },
	zir: { mime: 'application/vnd.zul', name: 'Z.U.L. Geometry' },
	zip: { mime: 'application/zip', name: 'Zip Archive' },
	zmm: { mime: 'application/vnd.handheld-entertainment+xml', name: 'ZVUE Media Manager' },
	zaz: { mime: 'application/vnd.zzazz.deck+xml', name: 'Zzazz Deck' },
	sql: { mime: 'application/sql,application/octet-stream', name: 'SQL' },
	heic: { mime: 'image/heic', name: 'High Efficiency Image Format' },
	heif: { mime: 'image/heif', name: 'High Efficiency Image Format' },
	heics: { mime: 'image/heic-sequence', name: 'High Efficiency Image Format' },
	heifs: { mime: 'image/heif-sequence', name: 'High Efficiency Image Format' },
	hej2: { mime: 'image/hej2k', name: 'High Efficiency Image Format' },
	hej2s: { mime: 'image/hej2k-sequence', name: 'High Efficiency Image Format' },
}
